
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 0
      logic-not-delete-value: 1
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


spring:
  application:
    name: mymall-product
  thymeleaf:
    cache: false
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      password: root
      username: root
      url: jdbc:mysql://localhost:3306/mymall_pms?useUnicode=true&characterEncoding=UTF-8
      # 连接池配置
      # 配置初始化大小、最小、最大
      initial-size: 5
      max-active: 20
      min-idle: 5
      # 获取连接等待超时时间
      max-wait: 60000
      pool-prepared-statements: true
      #
      validation-query: SELECT 1
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      # 间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      # 一个连接在连接池中最小的生存时间
      min-evictable-idle-time-millis: 300000
      max-pool-prepared-statement-per-connection-size: 20
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      filters: stat

      # 监控配置
      # Druid WebStatFilter配置
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.gif,*.png,*.jpg,*.html,*.js,*.css,*.ico
        # Druid StatViewServlet配置
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        # 登录监控界面的用户名以及密码，登录url为localhost:8080/druid
        login-username: admin
        login-password: admin
        allow:
        deny:
      filter:
        stat:
          slow-sql-millis: 200
          log-slow-sql: true
      jpa:
        show-sql: true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:3333
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    static-path-pattern: /static/**
  redis:
    host: 127.0.0.1
    port: 6382

#  resources:
logging:
  level:
    com.tracy.mymall: error
#    static-locations: classpath:/resources/static/**

---
spring:
  profiles: test1
server:
  port: 9500
---
spring:
  profiles: test2
server:
  port: 9400