server:
  port: 9505

spring:
  application:
    name: mymall-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # 动态路哟
      routes:
        - id: mymall-coupon-route
          uri: lb://mymall-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
          # 路径重写
            - RewritePath=/api(?<segment>/?.*), /$\{segment}
        - id: mymall-member-route
          uri: lb://mymall-member
          predicates:
            - Path=/api/member/**
          # 路径重写

          filters:
            - RewritePath=/api(?<segment>/?.*), /$\{segment}
        - id: mymall-ware-route
          uri: lb://mymall-ware
          predicates:
            - Path=/api/ware/**
          filters:
          # 路径重写
            - RewritePath=/api(?<segment>/?.*), /$\{segment}
        - id: mymall-order-route
          uri: lb://mymall-order
          predicates:
            - Path=/api/order/**
        - id: mymall-product-route
          uri: lb://mymall-product
          predicates:
            - Path=/api/product/**,/hello/**
          filters:
            # 路径重写
            - RewritePath=/api(?<segment>/?.*), /$\{segment}
        - id: mymall-thirdpart-route
          uri: lb://mymall-thirdpart
          predicates:
            - Path=/api/thirdpart/**
          filters:
          # 路径重写
            - RewritePath=/api/thirdpart(?<segment>/?.*), /$\{segment}
        - id: admin-renrenfast-route
          uri: lb://renren-fast
          predicates:
            #/api/** 需要放到最后，防止拦截更精确的路径
            - Path=/api/**
          filters:
            # 路径重写，其中后面的/renren-fast代表需要访问的服务tomcat配置的servelet context-path
            - RewritePath=/api(?<segment>/?.*), /renren-fast/$\{segment}
        # nginx反向代理访问mymall.com:1111后转向的地址
        - id: mymall_nginx_route
          uri: lb://mymall-product
          predicates:
            - Host=**.mymall.com


    nacos:
      discovery:
        server-addr: 127.0.0.1:3333
