server:
  port: 9509

spring:
  application:
    name: mymall-auth-server
  thymeleaf:
    cache: false
  cloud:
    nacos:
      discovery:
        server-addr: localhost:3333
  redis:
    host: 127.0.0.1
    port: 6382
  session:
    redis:
      namespace: spring:session
    store-type: redis
    timeout: 30m
