server:
  port: 9508


spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:3333
  application:
    name: mymall-cart
  redis:
    host: localhost
    port: 6382
  session:
    redis:
      namespace: spring:session
    store-type: redis
    timeout: 30m