server:
  port: 9502
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

spring:
  application:
    name: mymall-order
  datasource:
    # 手动注入的datgasource，给seata使用
    type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver        #mysql驱动包
    url: jdbc:mysql://localhost:3306/mymall_oms?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

    #DRUID自动注入的datasource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      password: root
      username: root
      url: jdbc:mysql://localhost:3306/mymall_oms?useUnicode=true&characterEncoding=UTF-8
      # 连接池配置
      # 配置初始化大小、最小、最大
      initial-size: 5
      max-active: 20
      min-idle: 5
      # 获取连接等待超时时间
      max-wait: 60000
      pool-prepared-statements: true
      #
      validation-query: SELECT 1
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      # 间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      # 一个连接在连接池中最小的生存时间
      min-evictable-idle-time-millis: 300000
      max-pool-prepared-statement-per-connection-size: 20
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      filters: stat

      # 监控配置
      # Druid WebStatFilter配置
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.gif,*.png,*.jpg,*.html,*.js,*.css,*.ico
        # Druid StatViewServlet配置
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        # 登录监控界面的用户名以及密码，登录url为localhost:8080/druid
        login-username: admin
        login-password: admin
        allow:
        deny:
      filter:
        stat:
          slow-sql-millis: 200
          log-slow-sql: true
      jpa:
        show-sql: true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:3333
    alibaba:
      seata:
        # 自定义事务组名称需要与seata-server中的对应
        tx-service-group: my_test_tx_group
  redis:
    host: localhost
    port: 6382
  session:
    redis:
      namespace: spring:session
    store-type: redis
    timeout: 30m
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: mymall-order
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    listener:
      ack-mode: manual
  thymeleaf:
    cache: false

