server:
  port: 9510

spring:
  application:
    name: mymall-secondkill
  cloud:
    nacos:
      discovery:
        server-addr: localhost:3333
  redis:
    port: 6382
    host: localhost
  session:
    redis:
      namespace: spring:session
    store-type: redis
    timeout: 30m
  thymeleaf:
    cache: false

